name: Alpine

on:
  push:

jobs:
  check:
    name: check version
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: |
          git clone https://github.com/mohsenmottaghi/docker-openresty-prometheus.git
      - name: Get latest version
        run: |
          LATEST=$(curl https://github.com/openresty/openresty/releases/latest | cut -d '"' -f 2 | cut -d '/' -f 8)
          echo -e "----------------------------\n\nThe Latest Version of OpenRasty is $LATEST\n\n----------------------------"
      - name: Build Docker image alpine
        run: |
          docker build -f docker-openresty-prometheus/alpine/Dockerfile -t openrasty:alpine-test .
      - name: Test Docker image
        run: |
          docker run --rm openrasty:alpine-test nginx -t